dist: xenial
language: minimal
services:
  - docker

env:
  global:
    - SLUG="${TRAVIS_REPO_SLUG/docker-/}"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - mkdir /media/DockerDownloads
  - mkdir /media/DockerData
  - mkdir /media/Data
  - docker-compose up -d
  - sleep 120
  # Display containers
  - docker ps --all
  # Detect if any containers are unhealthy and fail
  - docker ps --all | grep 'starting\|unhealthy' && return 1 || true
  # Inspect unhealthy containers
  - docker ps --all | grep 'starting\|unhealthy' | cut -f1 -d ' ' | xargs docker inspect || true
  # Display logs of unhealthy containers
  - docker ps --all | grep 'starting\|unhealthy' | cut -f1 -d ' ' | xargs docker logs || true
